# Generated by Django 5.0.2 on 2024-02-19 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_userprofile_bio_parts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio_parts',
        ),
    ]
