# Generated by Django 5.0.2 on 2024-02-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_remove_post_image_delete_image_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
