# Generated by Django 5.0.2 on 2024-02-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
