# Generated by Django 5.0.2 on 2024-02-23 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0019_friendrequest_is_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='is_rejected',
        ),
    ]
