# Generated by Django 5.0.2 on 2024-02-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_remove_friendrequest_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
