# Generated by Django 5.0.3 on 2024-03-05 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0027_helppost_meeting_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='studient',
            new_name='student',
        ),
    ]
