# Generated by Django 5.0.3 on 2024-03-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0029_request_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='topic',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
